// Auto-generated by scripts/gen-sw.mjs — do not edit by hand.
const VERSION = '74e58ccdd964';
const CACHE = 'earth-history-' + VERSION;
const ASSETS = [
  "./",
  "./index.html",
  "./assets/heights/.gitkeep",
  "./assets/index-Dr8MdPv_.css",
  "./assets/index-UPb5YaYA.js",
  "./assets/plate-atlas-DcJrbipv.png",
  "./assets/textures/README.md",
  "./assets/three-CgWYsrDb.js",
  "./assets/ui/.gitkeep",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./icons/icon-maskable.svg",
  "./icons/icon.svg",
  "./manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first for same-origin GETs; network only fills a miss. Fully offline
// once the first load completes. No cross-origin requests are made by the app.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => {
        // Navigation offline fallback → the cached shell.
        if (req.mode === 'navigate') return caches.match('./index.html');
      });
    })
  );
});
